[package]
name = "bytebit/signals-tooling"
description = "Simple, base-level tooling for working with signals in Roblox."
version = "1.0.8"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
